# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b5a9af8d5e570abb858d1a53792aa1bdeaffbd515df292d6a38248eed6807925a42b64a7e70cf6cb782099356ffe8da03f99b30ce54507df4453206113363e1

test:
  secret_key_base: e858f86d9d376954eeaceec402b9fb747a1074cd86d54396851b0c94568b5f17e0dc8bfcc340f5592759c7a33779235622fad38a266c15c53f5fe4d5de3b7949

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
